<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\data\equippable-items-full.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\NewFolder\" />
    <Folder Include="wwwroot\icons\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\data\equippable-items-full.json" />
  </ItemGroup>

</Project>
